### ISSUE TITLE
Tech@NYU logo not in the zip file?

### ISSUE THREAD

**Issue by jjmalina** [TechAtNYU/branding#1]
Hey, I just downloaded this and noticed we don't have the Tech@NYU logo in the zip at all. I just updated the style of the [HackDays meetup](http://www.meetup.com/nyhackdays/) but I wanted to put the Tech@NYU logo on the header as well, because otherwise it's impossible to tell that HackDays is a Tech@NYU initiative.

**Comment by revivek** [comment]
Ah good call. It's up.

On Sun, Feb 24, 2013 at 2:30 PM, Jeremiah Malina
notifications@github.comwrote:

> Hey, I just downloaded this and noticed we don't have the Tech@NYU logo
> in the zip at all. I just updated the style of the HackDays meetuphttp://www.meetup.com/nyhackdays/but I wanted to put the Tech@NYUlogo on the header as well, because otherwise it's impossible to tell that
> HackDays is a Tech@NYU initiative.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TechAtNYU/branding/issues/1.

## 

_Vivek Patel_
914.356.0778 · 1.vivekpatel@gmail.com · @revivekhttp://www.twitter.com/revivek
