### ISSUE TITLE
merge with styleguide?

### ISSUE THREAD

**Issue by grungerabbit** [TechAtNYU/branding#2]
Should this be merged with @irisyuan's styleguide?

**Comment by irisyuan** [comment]
Yes, can we create a new techatnyu repo?

**Comment by grungerabbit** [comment]
@ethanresnick what do you think?

**Comment by ethanresnick** [comment]
@grungerabbit I'm a bit confused. I thought this issue was about merging repos, rather than adding a new one? And since we want to keep the final repo on TechAtNYU, we'd presumably be merging @irisyuan's repo into this repo. Am I missing something?

**Comment by irisyuan** [comment]
@ethanresnick yeah, that's what I meant.

**Comment by ethanresnick** [comment]
Ok, awesome! Then let's do it. 

@irisyuan I'm giving you write permissions to this repo now, so you can add in the other content and use this repo going forward!
